-- UP Migration: Add all missing columns to integrations table
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "name" varchar(255) NOT NULL;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "app_url" varchar(255);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "app_logo" varchar(255);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "auth_url" varchar(255);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "app_description" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "integration_type" varchar(255);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "is_system_integration" boolean;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "created_at" timestamptz NOT NULL;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "json_url" varchar(255);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "category" text DEFAULT 'default';
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "info" varchar(255);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "is_paid" boolean DEFAULT false;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "is_approved" boolean DEFAULT false;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "prices" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "version" varchar(20) DEFAULT 'v1.0.0';
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "provider" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "default_input_modes" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "default_output_modes" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "pre_shared_key" varchar(64);
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "skills" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "owner_id" uuid;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "is_system" boolean DEFAULT false;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "commission_rate" numeric(5, 2) DEFAULT 80;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "capabilities" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "tone" varchar(255) DEFAULT 'friendly';
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "system_prompts" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "snapshot" jsonb;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "how_it_works" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "benefits" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "why_use" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "stars" int8 DEFAULT 1;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "short_description" text;
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "long_description" text;
