ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(255);
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS track VARCHAR(255);
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS links TEXT[];
