FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@v1.61.5

COPY go.mod go.sum ./

RUN go mod download

COPY . .
EXPOSE 8019

CMD ["air", "-c", ".air.toml"]