name: Build Golang Binary and Run Tests

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - testing

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Validate swagger.yaml
        uses: GrantBirki/json-yaml-validate@v3.1.0
        with:
          files: ./static/swagger.yaml
          
      - name: Setup app.env
        run: echo "${{ secrets.APP_ENV }}" > app.env

      - name: Build the application
        run: go build -o telex_be
      - name: Run the application
        run: nohup ./telex_be > /dev/null 2>&1 &
      - name: Wait for application to start
        run: |
          for i in {1..30}; do
            curl -s http://localhost:41010 && break
            sleep 1
          done
      - name: Run All Tests
        run: go test ./tests/... -timeout 300s
