name: Dev Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  update_repo_with_env:
    runs-on: self-hosted
    if: github.event.repository.fork == false
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create app.env file
        uses: vicradon/create-env-action@v1.0.1
        with:
          action_input_file: "app-sample.env"
          action_output_file: "app.env"
          action_true_string_variables: |
            MAIL_PASSWORD
            BUKCET_SECRET_KEY
            TYPESENSE_API_KEY
            CENTRIFUGE_API_KEY
          APP_NAME: "telex_be"
          APP_URL: "https://api-golang.boilerplate.hng.tech"
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_DB: "0"
          MIGRATE: "true"
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
          RESET_PASSWORD_DURATION: ${{ secrets.RESET_PASSWORD_DURATION }}
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
          BUKCET_SECRET_KEY: ${{ secrets.BUKCET_SECRET_KEY }}
          TYPESENSE_API_URL: ${{ secrets.TYPESENSE_API_URL }}
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY}}
          IPSTACK_KEY: ${{ secrets.IPSTACK_KEY }}
          IPSTACK_BASE_URL: ${{ secrets.IPSTACK_BASE_URL }}
          CENTRIFUGE_URL: ${{ secrets.CENTRIFUGE_URL }}
          CENTRIFUGE_API_KEY: ${{ secrets.CENTRIFUGE_API_KEY }}

      - name: Copy app.env to server
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key.pem
          chmod 400 ssh_key.pem
          scp -o StrictHostKeyChecking=no -i ssh_key.pem app.env ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/deployments/telex_be/app.env
          rm ssh_key.pem

  build_and_restart_app:
    runs-on: self-hosted
    needs: [update_repo_with_env]
    if: github.event.repository.fork == false
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Restart app
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key.pem
            chmod 600 ssh_key.pem
            ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            cd ~/deployments/telex_be
            git reset --hard
            git pull origin dev
            go build -o telex_be
            pm2 restart telex_be
          '

      - name: Remove ssh_key
        run: rm ssh_key.pem
