name: Deploy Telex Backend - main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_and_restart_app:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.TELEX_SERVER_SSH_USER }}
      SSH_HOST: ${{ secrets.TELEX_SERVER_SSH_HOST }}
      SSH_PASSWORD: ${{ secrets.TELEX_SERVER_SSH_PASSWORD }}
      BRANCH: main
      APP_DIR: /var/www/telex_be
      APP_BINARY: telexbe_main
      SUPERVISOR_PROCESS: telexbe
    steps:
      - name: Install sshpass
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Build and stop on failure
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
            cd '"$APP_DIR"'
            git reset --hard
            git pull origin '"$BRANCH"'
            go build -o '"$APP_BINARY"'
          '
      
      - name: Run DB migrations
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
            cd '"$APP_DIR"'
            echo "Running DB migrations..."
            yes | make migrate-safe-up
          '

      - name: Restart app
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
            supervisorctl restart '"$SUPERVISOR_PROCESS"'
          '
