name: Deploy Telex Backend - staging

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  update_env_and_binary:
    runs-on: self-hosted
    if: github.event.repository.fork == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'staging'

      - name: Build binary
        run: |
          go build -o telexbe_staging

      - name: Upload binary to server and restart app
        run: |
          echo "$SSH_KEY" > ssh_key.pem
          ssh_host='${{ vars.open_ssh_host }}'
          ssh_user='${{ vars.open_ssh_user }}'
          ssh_key='${{ vars.open_ssh_key }}'

          echo $ssh_host
          echo $ssh_user
          echo $ssh_key

          
          chmod 400 ssh_key.pem
          rsync -avz -e "ssh -i ssh_key.pem" telexbe_staging $ssh_user@$ssh_host:~/deployments/telexbe/staging/telexbe_staging

          rm ssh_key.pem
          
  update_and_restart_app:
    runs-on: self-hosted
    needs: [update_env_and_binary]
    if: github.event.repository.fork == false
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Restart app
        run: |
          echo "$SSH_KEY" > ssh_key.pem
            chmod 400 ssh_key.pem
            ssh -o StrictHostKeyChecking=no -i ssh_key.pem "$SSH_USERNAME"@"$SSH_HOST" '
            cd ~/deployments/telexbe/staging/
            git reset --hard
            git pull origin staging
            pm2 restart telexbe_staging
          '
          
      - name: Remove ssh_key
        run: rm ssh_key.pem
