name: Deploy Telex Backend - staging

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  update_and_restart_app:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.TELEX_SERVER_SSH_USER }}
      SSH_HOST: ${{ secrets.TELEX_SERVER_SSH_HOST }}
      SSH_PASSWORD: ${{ secrets.TELEX_SERVER_SSH_PASSWORD }}
      BRANCH: staging
      APP_DIR: /var/www/telex_be_staging
      APP_BINARY: telexbe_staging
      SUPERVISOR_PROCESS: telexbe_staging
    steps:
      - name: Install sshpass
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Build and stop on failure
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
            cd $APP_DIR
            git reset --hard
            git pull origin $BRANCH
            go build -o $APP_BINARY
          '

      - name: Restart app
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
            supervisorctl restart $SUPERVISOR_PROCESS
          '
