name: Run Cypress Tests Every 15 Minutes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install project dependencies
        run: |
          npm ci
          npm install cypress cypress-mochawesome-reporter

      - name: Run Cypress tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npx cypress run --e2e --reporter cypress-mochawesome-reporter

      - name: Generate Mochawesome report
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json
          npx mochawesome-report-generator cypress/reports/mochawesome.json --reportDir cypress/reports/html

      - name: Copy artifacts
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          source: "cypress/reports"
          target: "/home/vicradon/deployments/cypress-report/telex-fe"
